const ATTRIBUTES = {
  CONTRACT_GET_ONE: 'CONTRACT_GET_ONE',
  CONTRACT_GET_ALL: 'CONTRACT_GET_ALL',
  JOB_UNPAID: 'JOB_UNPAID',
  JOB_PAY: 'JOB_PAY',
  CLIENT_DEPOSIT: 'CLIENT_DEPOSIT',
};

module.exports = ATTRIBUTES;
